### PR TITLE
Add sword variants

### PR DESCRIPTION
**Pull request by zzuf-fer**
Creates 2 folders in the `customizations` directory, which contain alternate variants for sword items.

* short_swords
Takes the regular swords from PlastPack but removes a few pixels at the top. These changes are pretty common in PvP resource packs, and I've been asked by other people who use this pack to share these shorter versions (which is what gave me the idea for this pull request, really).

* octc_swords
These ones are a bit different: They are also shorter swords, but they're based on the swords featured in the Overcast logo (mixed in with PlastPack's slimmer designs).

I've been privately using these variants for a while, but as this pack already contains alternate textures for other things, I thought they could make a good addition!

### CODE REVIEW

**Comment by Brottweiler** [comment]
@Plastix Thoughts on this?

I do like the short versions, and I know they are popular among PvPers these days.
I have a suggestion; the sword in this PR has a different point than the regular sword. What about making the point look more like the regular sword? See the embedded image as an example.

image

**Comment by Plastix** [comment]
I like these — Go for it! Thanks for the heads up.

**Comment by zzuf-fer** [comment]
@Brottweiler I've made an update that follows your suggestion. While I did prefer the more rounded edge, it is absolutely true that these ones are probably better as they look closer to their original counterparts.

Let me know what you think! Thanks 👍

**Review by Brottweiler — APPROVED** [review]

**Comment by Brottweiler** [comment]
Looks good! Thanks for this. I will add a contribution to the changelog and readme.

**Pull request merged**
